### PR TITLE
Api rewrite

### PR DESCRIPTION
**Pull request by tlycken**
This is the start of a complete rewrite of this library to open up the API for other types of interpolations than B-splines. So far only constant interpolation (and no extrapolation) is implemented, but I think this shows clear enough where I want this to go, so I figure this is as good a time as any to ask for feedback.

The API will mainly affect how interpolation objects are constructed. What was previously

```julia
itp = Interpolation(A, Constant(OnCell), ExtrapError)
```
will now become

```julia
itp = interpolate(A, BSpline(Constant), OnCell)
exp = extrapolate(itp, Error) # but with a name that doesn't collide - suggestions?
```

I have a couple of reasons I want to make this change:

* We don't hog the name `Interpolation` for B-splines specifically - now, any type of interpolation can add methods to the `interpolate` function, with their own configuration type. Thus, I hope it will be easier to extend the package with things like simplex (see #28), Chebyshev (see #30) or Hermite spline (see #6) interpolation.

* Extrapolation is now even more separated from interpolation, which means that when e.g. linear extrapolation is implemented once, it will be re-usable across all interpolation types, and not only for B-splines. This can hopefully speed things up a little as well; if you *know* you're not going to extrapolate, you never have to bounds-check when indexing into an interpolation object.

* Other things, like scaling uniform grids from the unit grid `1:n` to other coordinate ranges, i.e. what `CoordInterpGrid` does in `Grid.jl`, also become re-usable across interpolation types, with a similar API.

Even if you don't have anything else to say about it than "OK with me", I'd love to hear some feedback on this.

The timeline for this rewrite is a little unclear - I have a lot on my table over the coming month, so progress will be slow. However, most of it is just shuffling code around, so it's perfectly possible to re-use other improvements made to the package in the meantime.

### CODE REVIEW

**Comment by tlycken** [comment]
(No, I haven't updated the tests to use this API yet, so they'll all fail miserably... I run some sanity tests with plots in the meantime, and they seem to give plausible results.)

**Comment by timholy** [comment]
Sorry, I completely missed this. (April was really busy.) :+1: for the idea. I'll try to find some time to help with this.

**Comment by tlycken** [comment]
:smiley: 

I have gotten quite far on porting quadratic interpolation as well, but haven't gotten around to pushing the changes yet; testing is the area where I've made absolutely the least progress. So if you do find some time, porting the tests is probably where the risk of duplicated work is the least .)

As you have exposed some areas with room for improvement, I'll try to get to this asap, so we can build from a common platform.

**Comment by timholy** [comment]
OK, I'll wait to do anything until you let me know you've updated this branch.

**Comment by tlycken** [comment]
I've now rebased this onto master. There were a few conflicts, in which I doubt I managed to salvage all the recent changes to master, so I'd be glad if you could take this for a spin.

The old version of this branch is available as `api-rewrite-backup` if we'd want to go back to it.

**Comment by tlycken** [comment]
@timholy, Now that the tests pass, I think this is a solid platform to build upon.

I don't know how widely this package is used, but I could tag a version on master (to get your compatibility fixes there) and then merge this and tag again (minor bump for pre-release breaking changes?) to make collaboration easier. What do you think?

**Comment by timholy** [comment]
This looks awesome. Sure, go ahead and tag master. Meanwhile I'll check out this branch and then start adding to it.

**Comment by timholy** [comment]
Bump. Anything I can do to help merge this? If it's just "tag current master, then merge and re-tag" I can do that for you.

**Comment by tlycken** [comment]
Sorry - I really had hoped I would have gotten to this by now. There are (always) more stuff I'd like to get done here, but for now I think this will have to do so I stop blocking you :)

Yes, a "tag current, then merge, then tag again" is what I had in mind. Given that the API is nowhere near backwards-compatible, I think 0.0.2 - merge - 0.1.0 is reasonable. Fire at will!

**Comment by tlycken** [comment]
Thanks a lot for helping me land this, @timholy. As always, you're invaluable :)

**Pull request merged**
