### PR TITLE
remove trailing - from julia version in REQUIRE

### PR DESCRIPTION
**Pull request by tkelman**
unless you have a need to still support pre-releases of julia 0.4

### CODE REVIEW

**Comment by tlycken** [comment]
Thanks.

The Travis failure is unrelatedm; @timholy, is this test failure what #97 is intended to address?

**Comment by tkelman** [comment]
most likely, ref http://pkg.julialang.org/detail/Interpolations.html

**Comment by tlycken** [comment]
Yup, noticed that the other day too (I wonder why PkgEval didn't file an issue here about it...). I've merged #97 now, where tests pass.

This change really shouln't be a problem in any way, but I feel a little uneasy merging things with failing tests. Do you mind rebasing? If you have more important things to do, I'll rebase and check myself when I get home from work.

**Comment by tkelman** [comment]
I did this from the web interface. I can ssh into something that's not a phone, clone and rebase but I think if you click restart on travis it would fetch a new merge commit to latest master.

**Comment by timholy** [comment]
Thanks, @tkelman.

**Comment by tlycken** [comment]
Ah, I see. Thanks!

**Pull request merged**
