### PR TITLE
Fix0.6

### PR DESCRIPTION
**Pull request by jw3126**
This fixes all errors and warnings with Julia v0.6. #134

### CODE REVIEW

**Comment by timholy** [comment]
I'm tagging a new WoodburyMatrices now, and AxisAlgorithms shortly. Should help reading the travis logs. Sorry I didn't do that earlier.

**Comment by jw3126** [comment]
Thanks! I think the reason for nightly failure is too many depwarns from untagged depdendencies.

**Comment by timholy** [comment]
OK, looks like they've both been tagged.

**Comment by sglyon** [comment]
Checks pass! Good work, all

**Comment by timholy** [comment]
I'm going to hit merge on this, thanks @jw3126!

**Comment by timholy** [comment]
I should have squashed, sorry about that. Too late now.

@tlycken, the rest of the Julia world is migrating to [attobot](https://github.com/attobot/attobot). I think you're the only one who can turn it on for Interpolations. Meanwhile, I'm going to tag a release the old-fashioned way.

**Pull request merged**
