### PR TITLE
speed up size, lbounds, and ubounds with @generated functions

### PR DESCRIPTION
**Pull request by rdeits**
`size()`, `lbounds()`, and `ubounds()` currently use the `ntuple(i -> f(i), N)` syntax, which is rather slow. A generated function makes the return type inferable without any type assertions and also improves performance. It also has the side-effect of fixing an apparent typeassert bug in `lbounds` and `ubounds`. 

## Before

```julia
julia> using BenchmarkTools

julia> A = rand(2,2,2)
2×2×2 Array{Float64,3}:
[:, :, 1] =
 0.771663  0.124192
 0.524341  0.676021

[:, :, 2] =
 0.295365  0.966051
 0.585499  0.599789

julia> itp = interpolate(A, BSpline(Linear()), OnGrid())
2×2×2 Interpolations.BSplineInterpolation{Float64,3,Array{Float64,3},Interpolations.BSpline{Interpolations.Linear},Interpolations.OnGrid,0}:
[:, :, 1] =
 0.771663  0.124192
 0.524341  0.676021

[:, :, 2] =
 0.295365  0.966051
 0.585499  0.599789

julia> @benchmark size($itp)
BenchmarkTools.Trial:
  memory estimate:  48.00 bytes
  allocs estimate:  2
  --------------
  minimum time:     75.793 ns (0.00% GC)
  median time:      78.353 ns (0.00% GC)
  mean time:        90.578 ns (3.68% GC)
  maximum time:     3.053 μs (93.58% GC)
  --------------
  samples:          10000
  evals/sample:     970
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.lbounds($itp)
ERROR: TypeError: typeassert: expected Tuple{Float64,Float64,Float64}, got Tuple{Int64,Int64,Int64}
 in ##core#280() at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:250
 in ##sample#281(::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:257
 in #_run#2(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#279")}, ::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:285
 in (::BenchmarkTools.#kw##_run)(::Array{Any,1}, ::BenchmarkTools.#_run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#279")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in anonymous at ./<missing>:?
 in #run#17(::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#279")}, ::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:32
 in (::Base.#kw##run)(::Array{Any,1}, ::Base.#run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#279")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in warmup(::BenchmarkTools.Benchmark{Symbol("##benchmark#279")}) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:67

julia> @benchmark Interpolations.ubounds($itp)
ERROR: TypeError: typeassert: expected Tuple{Float64,Float64,Float64}, got Tuple{Int64,Int64,Int64}
 in ##core#284() at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:250
 in ##sample#285(::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:257
 in #_run#3(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#283")}, ::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:285
 in (::BenchmarkTools.#kw##_run)(::Array{Any,1}, ::BenchmarkTools.#_run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#283")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in anonymous at ./<missing>:?
 in #run#17(::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#283")}, ::BenchmarkTools.Parameters) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:32
 in (::Base.#kw##run)(::Array{Any,1}, ::Base.#run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#283")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in warmup(::BenchmarkTools.Benchmark{Symbol("##benchmark#283")}) at /Users/rdeits/.julia/v0.5/BenchmarkTools/src/execution.jl:67
```

## After

```julia
julia> using BenchmarkTools

julia> A = rand(2,2,2);

julia> itp = interpolate(A, BSpline(Linear()), OnGrid());

julia> @benchmark size($itp)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.691 ns (0.00% GC)
  median time:      3.752 ns (0.00% GC)
  mean time:        3.836 ns (0.00% GC)
  maximum time:     16.309 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.lbounds($itp)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.695 ns (0.00% GC)
  median time:      1.739 ns (0.00% GC)
  mean time:        1.785 ns (0.00% GC)
  maximum time:     24.235 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.ubounds($itp)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.964 ns (0.00% GC)
  median time:      5.989 ns (0.00% GC)
  mean time:        6.923 ns (0.00% GC)
  maximum time:     41.035 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

### CODE REVIEW

**Comment by rdeits** [comment]
Also, if you'd rather avoid `@generated` functions here, a trivial improvement would be to change `ntuple(i -> f(i), N)` to `ntuple(i -> f(i), Val{N})`.

**Comment by sglyon** [comment]
Looks good to me

**Comment by timholy** [comment]
Sorry I didn't notice this. Yes, it would be better to use the `Val{N}` form. Would you mind?

**Comment by rdeits** [comment]
Ok, I've switched to the `Val{N}` form and rebased. Performance is slightly worse than `@generated` but still an improvement over the original:

```julia
julia> @benchmark size($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     17.439 ns (0.00% GC)
  median time:      19.440 ns (0.00% GC)
  mean time:        22.403 ns (3.33% GC)
  maximum time:     1.231 μs (96.20% GC)
  --------------
  samples:          10000
  evals/sample:     998
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.lbounds($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     11.905 ns (0.00% GC)
  median time:      13.343 ns (0.00% GC)
  mean time:        15.039 ns (5.08% GC)
  maximum time:     1.184 μs (96.23% GC)
  --------------
  samples:          10000
  evals/sample:     998
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.ubounds($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     16.777 ns (0.00% GC)
  median time:      18.742 ns (0.00% GC)
  mean time:        22.057 ns (3.95% GC)
  maximum time:     1.865 μs (95.66% GC)
  --------------
  samples:          10000
  evals/sample:     998
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by timholy** [comment]
Hmm, I'm surprised it's different. Is it enough of an improvement that you're fine with it? Or can you see that this has a cost in "real" code? With apologies for my inconsistent statements, we could go back to `@generated` if you think the gap makes a difference.

**Comment by rdeits** [comment]
My understanding is that the ntuple form creates the closure `i -> size(itp, i)` which contains a reference to non-bitstype `itp` and therefore allocates. The `@generated` form, on the other hand, doesn't create a closure and therefore can avoid allocation entirely. 

Honestly, I've forgotten why I needed `size()` to be faster. I think it came up when I was trying to optimize part of https://github.com/rdeits/regiontrees.jl down to zero allocations, so, for that case, the `@generated` form has an advantage. 

But I'm happy with whatever you prefer. I know there's a general trend to try to avoid `@generated` functions (something about it making certain compiler optimizations harder?).

**Comment by timholy** [comment]
Does it help if you add `@inline` in front of those definitions?

**Comment by rdeits** [comment]
No, `@inline` seems to make no difference: 

```
julia> @benchmark size($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     16.954 ns (0.00% GC)
  median time:      17.601 ns (0.00% GC)
  mean time:        19.300 ns (3.52% GC)
  maximum time:     1.065 μs (95.72% GC)
  --------------
  samples:          10000
  evals/sample:     998
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.lbounds($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     9.969 ns (0.00% GC)
  median time:      11.243 ns (0.00% GC)
  mean time:        12.644 ns (6.40% GC)
  maximum time:     1.443 μs (97.08% GC)
  --------------
  samples:          10000
  evals/sample:     999
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Interpolations.ubounds($itp)
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     16.784 ns (0.00% GC)
  median time:      17.393 ns (0.00% GC)
  mean time:        18.690 ns (3.32% GC)
  maximum time:     1.088 μs (96.15% GC)
  --------------
  samples:          10000
  evals/sample:     997
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by timholy** [comment]
OK, let's go with this version, and anyone who really needs it can go the `@generated` route.

Thanks, @rdeits!

**Comment by rdeits** [comment]
Looks like type inference of `size()` is failing in julia v0.4. Is that because it can't infer the return type of the anonymous function `i -> size(itp, i)` ?

**Comment by rdeits** [comment]
I think *that* might be a sufficiently compelling argument for the `@generated` version, which should be inferred correctly in any julia version.

**Comment by timholy** [comment]
Sure, let's go back to the generated function. Sorry about that.

**Comment by rdeits** [comment]
ok, let's see if that passes

**Comment by timholy** [comment]
Thanks, @rdeits!

**Pull request merged**
