### PR TITLE
Apply compat updates for Julia 0.6

### PR DESCRIPTION
**Pull request by ararslan**
This should fix the deprecation warnings on 0.6.

### CODE REVIEW

**Comment by ararslan** [comment]
The only remaining deprecation warning specific to this package is from `Base.FloatRange`, and I'm not sure how best to deal with that; there doesn't appear to be a Compat solution for it.

**Comment by ararslan** [comment]
Ping @timholy -- does this look okay?

**Comment by timholy** [comment]
Thanks, @ararslan!

I wonder if we need some specializations for the new `LinSpace`, but it doesn't seem necessary to get the tests to pass (and that's really more an issue for the previous updates than this one).

**Comment by ararslan** [comment]
My pleasure! Any chance you could tag a patch release with these changes?

**Comment by timholy** [comment]
Sure. @tlycken, a reminder: could you turn on [attobot](https://github.com/attobot/attobot)? No one but you can do that.

**Comment by tlycken** [comment]
@timholy Thanks for the reminder, I think it should be done now!

**Comment by ararslan** [comment]
Thanks all! 🙂

**Pull request merged**
